### ISSUE TITLE
How to pass runtime arguments for java native image

### ISSUE THREAD

**Issue by zhoufenqin** [paketo-buildpacks/java-native-image#610]
Env:
kpack 0.9.2
k8s

If I want to [enable JFR with Native Image](https://www.graalvm.org/22.3/reference-manual/native-image/debugging-and-diagnostics/JFR/), then in the build phase, I will pass a build argument like `BP_NATIVE_IMAGE_BUILD_ARGUMENTS="--no-fallback --enable-monitoring=jfr --enable-monitoring=jvmstat" `.

In runtime, I should configure JFR `-XX:+FlightRecorder -XX:StartFlightRecording="filename=recording.jfr"` to enable JFR and start a recording

For an pod spec, it looks like
```
  spec:
      containers:
      - args:
        - -XX:+FlightRecorder
        - -XX:StartFlightRecording=filename=/tmp/troubleshooting/recording.jfr,dumponexit=true,duration=10s
        command:
        - /cnb/process/web
```

But I hope the argument can be passed in another way. Like in [OpenJDK buildpack](https://github.com/paketo-buildpacks/microsoft-openjdk),  we will set `BPL_JFR_ENABLED = true`, then `-XX:StartFlightRecording=dumponexit=true,filename=/tmp/recording.jfr` will be automatically injected into JAVA_TOOL_OPTION when starting the java process.

Not sure if there are similar operations in a native image, we can pass some runtime environment, then `/cnb/process/web` will pick up some env as runtime parameters?

## Expected Behavior
we don't need to configure each args manually, just configure some `BPL_` env to represent the runtime environments.

## Current Behavior
we should define args for each native image feature
